//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice_12
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_Control
    {
        public byte[] timestamp { get; set; }
        public System.Guid User_Security_ID { get; set; }
        public string Role_ID { get; set; }
        public string Company_Name { get; set; }
        public int Scope { get; set; }
        public System.Guid App_ID { get; set; }
    }
}
